branch-defaults:
  master:
    environment: typecodebackend-dev
environment-defaults:
  typecodebackend-stage:
    branch: null
    repository: null
global:
  application_name: typecodebackend
  default_ec2_keyname: typecode
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: typecode
  sc: git
  workspace_type: Application
